name: Github Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - "*"
      - "!master"
      - "!main"
  pull_request:
permissions:
  contents: read
jobs:
  Golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.2.2
